"""Add start_date and end_date to Group model

Revision ID: d26c2d5d9e87
Revises: 
Create Date: 2025-03-02 00:35:15.129379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd26c2d5d9e87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    op.drop_table('meals')
    op.drop_table('entry_tickets')
    op.drop_table('agreements')
    op.drop_table('quotes')
    op.drop_table('hotels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quote_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost_per_room', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high_occupancy_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('has_high_occupancy', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('tax_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('occupancy_options', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('high_occupancy_options', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_reusable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name='hotels_quote_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='hotels_pkey')
    )
    op.create_table('quotes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('quotes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bus_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metro_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('airline_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('train_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('guide_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('guide_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guide_tip', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('driver_tip', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('profit_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='quotes_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quotes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('agreements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quote_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name='agreements_quote_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='agreements_pkey')
    )
    op.create_table('entry_tickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quote_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name='entry_tickets_quote_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='entry_tickets_pkey')
    )
    op.create_table('meals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quote_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name='meals_quote_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='meals_pkey')
    )
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('num_paying', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chaperone_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('num_chaperones', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chaperone_ratio', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='groups_pkey')
    )
    # ### end Alembic commands ###
